name: ibl-neuropixel CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    name: build (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]
    steps:
      - name: Checkout ibl-neuropixel repo
        uses: actions/checkout@v3
        with:
          path: ibl-neuropixel

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: flake8
        run: |
          pip install flake8>=7 --quiet
          cd ibl-neuropixel
          python -m flake8

      - name: iblrig and iblpybpod requirements
        shell: bash -l {0}
        run: |
          pip install -e ibl-neuropixel
          pip install -r ibl-neuropixel/requirements.txt

      - name: CPU unit tests
        shell: bash -l {0}
        run: |
          cd ibl-neuropixel/src/tests/unit/cpu
          python -m unittest discover
